### ISSUE TITLE
chore: move from standard-version to release-please

### ISSUE THREAD

**Issue by billchurch** [billchurch/webssh2_client#10]
### Package.json Issues
1. Missing required fields:
   - No clear `description`
   - Empty `author` field
   - Non-standard license field format
   - No clear `repository.directory` for monorepo support

2. Release Script Issues:
   - Current scripts tightly coupled with standard-version
   - Build step embedded in version bump process
   - No clear distinction between versioning and publishing

### 1. Package.json Updates

```json
{
  "name": "webssh2_client",
  "version": "0.2.27",
  "description": "A web-based SSH2 client component for WebSSH2",
  "author": "Bill Church",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/billchurch/webssh2_client.git",
    "directory": "."
  },
  "scripts": {
    // Remove standard-version scripts
    "build": "webpack --mode production --progress --config scripts/webpack.prod.js",
    "publish:dry-run": "npm publish --dry-run",
    "publish:npm": "npm publish"
  }
}
```

### 2. Setup Release Please

1. Create `.github/workflows/release-please.yml`:
```yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: webssh2_client
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":true}]'
```

2. Create `release-please-config.json`:
```json
{
  "packages": {
    ".": {
      "changelog-path": "CHANGELOG.md",
      "release-type": "node",
      "bump-minor-pre-major": false,
      "bump-patch-for-minor-pre-major": false,
      "draft": false,
      "prerelease": false
    }
  },
  "bootstrap-sha": "current-sha-here",
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

### 3. Remove standard-version Dependencies

1. Remove from package.json:
```diff
- "standard-version": "^9.5.0",
- "conventional-changelog-cli": "^5.0.0"
```

2. Remove standard-version config:
```diff
- "standard-version": {
-   "scripts": {
-     "postbump": "npm run build",
-     "precommit": "git add client/public/*"
-   }
- }
```

### 4. Setup GitHub Actions for Publishing

Create `.github/workflows/npm-publish.yml`:
```yaml
name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```

## Implementation Tasks

1. Package.json Updates
   - [x] Add missing fields (author, description)
   - [x] Fix license field format
   - [x] Remove standard-version configuration
   - [x] Update repository configuration
   - [x] Clean up release-related scripts

2. GitHub Configuration
   - [x] Create release-please workflow
   - [x] Create npm publish workflow
   - [ ] Add NPM_TOKEN secret to repository
   - [ ] Configure branch protection rules

3. Release Please Setup
   - [ ] Create release-please-config.json
   - [ ] Set correct bootstrap-sha
   - [ ] Configure changelog types
   - [ ] Test release workflow

4. Cleanup
   - [ ] Remove standard-version dependencies
   - [ ] Update documentation
   - [ ] Migrate existing changelog
   - [ ] Update contributing guidelines

## Migration Notes

1. Release Process Changes:
   - No more local version bumping
   - Automated changelog generation
   - PR-based release flow
   - Automated npm publishing

2. Commit Message Requirements:
   - Must follow conventional commits
   - Types: feat, fix, docs, style, refactor, test, chore

3. Breaking Changes:
   - Include `BREAKING CHANGE:` in commit message
   - Forces major version bump
   - Highlighted in changelog

## Post-Migration Verification

1. Check Release Process:
   - [ ] Verify PR creation
   - [ ] Confirm changelog updates
   - [ ] Test version bumping
   - [ ] Verify npm publishing

2. Documentation Updates:
   - [ ] Update README.md
   - [ ] Update CONTRIBUTING.md
   - [ ] Add release process documentation
   - [ ] Update development guides

3. Review Automation:
   - [ ] Test PR creation
   - [ ] Verify changelog generation
   - [ ] Confirm version bumping
   - [ ] Validate npm publishing
